### ISSUE TITLE
[Bug] Always show "new version found" when I am already have latest version.

### ISSUE THREAD

**Issue by aobao32** [DamonDeng/BRClient#22]
### Bug Description

Always show "new version found" when I am already have latest version.

### Steps to Reproduce

1. Go to settings
2. Below current version, it always says "New version found".

### Expected Behavior

If current version is up-to-date, the UI should report "Currently you are using latest version".

### Screenshots

![br-update](https://github.com/DamonDeng/BRClient/assets/12456320/c47ba1ea-ffe4-45dd-920b-60ec34e75de2)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

macos

**Comment by DamonDeng** [comment]
fixed in v1.11.8
